services:
  vaultwarden:
    image: vaultwarden/server:1.35.4-alpine@sha256:34b4e91ed4c2a4d2191245325608b2a84bedbeb9c9dd561e3c0924b98ef7126c
    container_name: vaultwarden
    hostname: vaultwarden
#    ports:
#      - 8000:80
    volumes:
      - /mnt/ssd/core/vaultwarden/data:/data:rw
    networks:
      - traefik
    environment:
      DOMAIN: ${DOMAIN}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      EXPERIMENTAL_CLIENT_FEATURE_FLAGS: ${EXPERIMENTAL_CLIENT_FEATURE_FLAGS}
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURITY: "force_tls"
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SSO_ENABLED: "true"
      SSO_ONLY: "true"
      SSO_SIGNUPS_MATCH_EMAIL: "true"
      SSO_AUTHORITY: ${SSO_AUTHORITY}
      SSO_SCOPES: "email profile groups"
      SSO_PKCE: "true"
      SSO_CLIENT_ID: ${SSO_CLIENT_ID}
      SSO_CLIENT_SECRET: ${SSO_CLIENT_SECRET}
      SSO_MASTER_PASSWORD_POLICY: '{"enforceOnLogin":false,"minComplexity":3,"minLength":10,"requireLower":true,"requireNumbers":true,"requireSpecial":true,"requireUpper":true}'
      SSO_AUTH_ONLY_NOT_SESSION: "false"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=cloudflare"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=cloudflarewarp@file,crowdsec@file"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"

      - "bunkerweb.USE_TEMPLATE=vaultwarden"
      - "bunkerweb.SERVER_NAME=${SERVICE_DOMAIN}"
      
      - "bunkerweb.USE_REVERSE_PROXY=yes"
      - "bunkerweb.USE_LIMIT_REQ=yes"
      #- "bunkerweb.LIMIT_REQ_URL=/"
      #- "bunkerweb.LIMIT_REQ_RATE=3r/s"
      #- "bunkerweb.LIMIT_REQ_URL_1=/identity/connect/authorize"
      #- "bunkerweb.LIMIT_REQ_RATE_1=5r/m"
      #- "bunkerweb.LIMIT_REQ_URL_2=/api/accounts"
      #- "bunkerweb.LIMIT_REQ_RATE_2=60r/m"
      # - "bunkerweb.BAD_BEHAVIOR_THRESHOLD=5"
      - "bunkerweb.CORS_ALLOW_ORIGIN=${OIDC_PROVIDER_DOMAIN} ${SERVICE_DOMAIN} ${PANGOLIN_DOMAIN}"
      - "bunkerweb.CORS_ALLOW_CREDENTIALS=yes"
      - "bunkerweb.USE_AUTH_BASIC=yes"
      - "bunkerweb.AUTH_BASIC_LOCATION=/admin"
      - "bunkerweb.AUTH_BASIC_USER=${VAULTWARDEN_BASIC_USER}"
      - "bunkerweb.AUTH_BASIC_PASSWORD=${VAULTWARDEN_BASIC_PASSWORD}"
      #- "bunkerweb.USE_CLIENT_CACHE=yes"
      #- "bunkerweb.USE_MODSECURITY=yes"
      #- "bunkerweb.USE_MODSECURITY_CRS=yes"
      #- |
      #  bunkerweb.CUSTOM_CONF_MODSEC_CRS_vaultwarden-import=
      #  SecAction "id:420001,phase:1,nolog,pass,t:none,setvar:'tx.allowed_methods=GET HEAD POST OPTIONS PUT DELETE'"

#        ## Make import to Org Possible by deaktivating XSS check
#        SecRule REQUEST_URI "@beginsWith /api/ciphers/import-organization" \
#          "id:420002,phase:1,pass,nolog,ctl:ruleRemoveById=941100"

#        ## Remove RCE attack since non windows systems are not vulnerable
#        SecRule REQUEST_URI "@beginsWith /api/ciphers/import-organization" \
#          "id:420003,phase:1,pass,nolog,ctl:ruleRemoveById=932110"

#        SecRule REQUEST_URI "@beginsWith /api/ciphers/import-organization" \
#          "id:420006,phase:1,pass,nolog,ctl:ruleRemoveById=932115"

#        ## Remove Test for Inbound XSS check
#        SecRule REQUEST_URI "@beginsWith /api/ciphers/import-organization" \
#          "id:420004,phase:1,pass,nolog,ctl:ruleRemoveById=949110"

#        ## XXS Test deactivated for Org Import
#        SecRule REQUEST_URI "@beginsWith /api/ciphers/import-organization" \
#          "id:420005,phase:1,pass,nolog,ctl:ruleRemoveById=941120"

      #    X-Frame-Options: SAMEORIGIN
      #    Content-Security-Policy: frame-ancestors 'self' *;
      #    Referrer-Policy: strict-origin-when-cross-origin

#      - "bunkerweb.USE_ANTIBOT=no"

networks:
  traefik:
    external: true
