services:
  vaultwarden:
    image: vaultwarden/server:1.35.4-alpine@sha256:34b4e91ed4c2a4d2191245325608b2a84bedbeb9c9dd561e3c0924b98ef7126c
    container_name: vaultwarden
    hostname: vaultwarden
#    ports:
#      - 8000:80
    volumes:
      - /mnt/ssd/core/vaultwarden/data:/data:rw
    networks:
      - bw-services
    environment:
      DOMAIN: ${DOMAIN}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      EXPERIMENTAL_CLIENT_FEATURE_FLAGS: ${EXPERIMENTAL_CLIENT_FEATURE_FLAGS}
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURITY: "force_tls"
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SSO_ENABLED: "true"
      SSO_ONLY: "false"
      SSO_SIGNUPS_MATCH_EMAIL: "true"
      SSO_AUTHORITY: ${SSO_AUTHORITY}
      SSO_SCOPES: "email profile groups"
      SSO_PKCE: "true"
      SSO_CLIENT_ID: ${SSO_CLIENT_ID}
      SSO_CLIENT_SECRET: ${SSO_CLIENT_SECRET}
      SSO_MASTER_PASSWORD_POLICY: '{"enforceOnLogin":false,"minComplexity":3,"minLength":10,"requireLower":true,"requireNumbers":true,"requireSpecial":true,"requireUpper":true}'
      SSO_AUTH_ONLY_NOT_SESSION: "false"
    labels:
      - "bunkerweb.SERVER_NAME=${SERVICE_DOMAIN}"
      - "bunkerweb.USE_REVERSE_PROXY=yes"
      - "bunkerweb.REVERSE_PROXY_HOST=http://vaultwarden:80"
      - "bunkerweb.SECURITY_MODE=detect"
      - "bunkerweb.USE_LIMIT_REQ=yes"
      - "bunkerweb.USE_LIMIT_REQ=yes"
      - "bunkerweb.LIMIT_REQ_URL=/"
      - "bunkerweb.LIMIT_REQ_RATE=30r/m"
      - "bunkerweb.LIMIT_REQ_URL_1=/identity/connect/authorize"
      - "bunkerweb.LIMIT_REQ_RATE_1=5r/m"
      - "bunkerweb.LIMIT_REQ_URL_2=/api/accounts"
      - "bunkerweb.LIMIT_REQ_RATE_2=60r/m"
      - "bunkerweb.BAD_BEHAVIOR_THRESHOLD=5"
      - "bunkerweb.CORS_ORIGIN=${OIDC_PROVIDER_DOMAIN} ${SERVICE_DOMAIN} ${PANGOLIN_DOMAIN}"
      - "bunkerweb.CORS_CREDENTIALS=yes"
      - "bunkerweb.USE_AUTH_BASIC=yes"
      - "bunkerweb.AUTH_BASIC_LOCATION=/admin"
      - "bunkerweb.AUTH_BASIC_USER=${VAULTWARDEN_BASIC_USER}"
      - "bunkerweb.AUTH_BASIC_PASSWORD=${VAULTWARDEN_BASIC_PASSWORD}"
      - "bunkerweb.USE_CLIENT_CACHE=no"
      - |
        bunkerweb.CUSTOM_HEADERS: |
          Permissions-Policy: publickey-credentials-get=(self), publickey-credentials-set=(self)
      #    X-Frame-Options: SAMEORIGIN
      #    Content-Security-Policy: frame-ancestors 'self' *;
      #    Referrer-Policy: strict-origin-when-cross-origin

#      - "bunkerweb.USE_ANTIBOT=no"

networks:
  bw-services:
    external: true
