name: pelican-panel
working_dir: apps/pelican-panel
compose_files:
  - compose.pelican-panel.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/gaming/pelican-panel/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/gaming/pelican-panel/SERVICE_NAME
  ADMIN_EMAIL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/gaming/pelican-panel/ADMIN_EMAIL
---
name: pelican-wings
working_dir: apps/pelican-wings
compose_files:
  - compose.pelican-wings.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/gaming/pelican-wings/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/gaming/pelican-wings/SERVICE_NAME
---
name: litellm
working_dir: apps/litellm
compose_files:
  - compose.litellm.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  LITELLM_DB_PASSWORD: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/litellm/LITELLM_DB_PASSWORD
  LITELLM_DB_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/litellm/LITELLM_DB_URL
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/litellm/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/litellm/SERVICE_NAME
  LITELLM_MASTER_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/litellm/LITELLM_MASTER_KEY
  OPENROUTER_API_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/litellm/OPENROUTER_API_KEY
  OPENROUTER_API_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/litellm/OPENROUTER_API_URL
---
name: open-webui
working_dir: apps/open-webui
compose_files:
  - compose.open-webui.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/SERVICE_NAME
  DATABASE_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/DATABASE_URL
  POSTGRES_USER: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/POSTGRES_USER
  POSTGRES_PASSWORD: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/POSTGRES_PASSWORD
  POSTGRES_DB: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/POSTGRES_DB
  POSTGRES_MULTIPLE_DATABASES: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/POSTGRES_MULTIPLE_DATABASES
  QDRANT_API_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/QDRANT_API_KEY
  REDIS_PASSWORD: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/REDIS_PASSWORD
  REDIS_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/REDIS_URL
  OPENID_PROVIDER_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/OPENID_PROVIDER_URL
  OAUTH_CLIENT_ID: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/OAUTH_CLIENT_ID
  OAUTH_CLIENT_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/OAUTH_CLIENT_SECRET
  OPENAI_API_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/OPENAI_API_KEY
  OPENAI_API_BASE_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/OPENAI_API_BASE_URL
  WEBUI_SECRET_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/WEBUI_SECRET_KEY
  OPEN_TERMINAL_API_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/OPEN_TERMINAL_API_KEY
  ROOT_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ROOT_DOMAIN
  EDGE_TTS_API_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/EDGE_TTS_API_KEY
  MCPO_API_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/open-webui/MCPO_API_KEY
---
name: backrest
working_dir: apps/backrest
compose_files:
  - compose.backrest.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/backrest/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/backrest/SERVICE_NAME
  BACKUP_USER: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/backrest/BACKUP_USER
  BACKUP_PASS: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/backrest/BACKUP_PASS
---
name: searxng
working_dir: apps/searxng
compose_files:
  - compose.searxng.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/searxng/SERVICE_NAME
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/searxng/SERVICE_DOMAIN
---
name: traefik
working_dir: apps/traefik
compose_files:
  - compose.traefik.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  CLOUDFLARE_API_EMAIL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/CLOUDFLARE_API_EMAIL
  CLOUDFLARE_DNS_API_TOKEN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/CLOUDFLARE_DNS_API_TOKEN
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/SERVICE_NAME
  ROOT_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ROOT_DOMAIN
  OIDC_SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/security/pocket-id/SERVICE_DOMAIN
  TRAEFIK_OIDC_CLIENT_ID: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/TRAEFIK_OIDC_CLIENT_ID
  TRAEFIK_OIDC_CLIENT_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/TRAEFIK_OIDC_CLIENT_SECRET
---
name: vaultwarden
working_dir: apps/vaultwarden
compose_files:
  - compose.vaultwarden.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  ADMIN_TOKEN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/ADMIN_TOKEN
  EXPERIMENTAL_CLIENT_FEATURE_FLAGS: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/EXPERIMENTAL_CLIENT_FEATURE_FLAGS
  DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/DOMAIN
  SMTP_HOST: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SMTP_HOST
  SMTP_FROM: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SMTP_FROM
  SMTP_USERNAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SMTP_USERNAME
  SMTP_PASSWORD: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SMTP_PASSWORD
  SSO_AUTHORITY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SSO_AUTHORITY
  SSO_CLIENT_ID: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SSO_CLIENT_ID
  SSO_CLIENT_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SSO_CLIENT_SECRET
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SERVICE_NAME
  OIDC_PROVIDER_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/OIDC_PROVIDER_DOMAIN
  VAULTWARDEN_BASIC_USER: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/VAULTWARDEN_BASIC_USER
  VAULTWARDEN_BASIC_PASSWORD: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/VAULTWARDEN_BASIC_PASSWORD
---
name: speedtest-tracker
working_dir: apps/speedtest-tracker
compose_files:
  - compose.speedtest-tracker.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  APP_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/monitoring/speedtest-tracker/APP_KEY
  APP_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/monitoring/speedtest-tracker/APP_URL
  SPEEDTEST_SERVERS: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/monitoring/speedtest-tracker/SPEEDTEST_SERVERS
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/monitoring/speedtest-tracker/SERVICE_NAME
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/monitoring/speedtest-tracker/SERVICE_DOMAIN
---
name: forgejo
working_dir: apps/forgejo
compose_files:
  - compose.forgejo.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  CF_CAPTCHA_SITEKEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/CF_CAPTCHA_SITEKEY
  CF_CAPTCHA_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/CF_CAPTCHA_SECRET
  MAIL_FROM: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/MAIL_FROM
  MAIL_HOST: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/MAIL_HOST
  MAIL_USER: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/MAIL_USER
  MAIL_PASSWD: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/MAIL_PASSWD
  NO_REPLY_ADDRESS: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/NO_REPLY_ADDRESS
  ROOT_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/ROOT_URL
  DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/DOMAIN
  SSH_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/SSH_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/SERVICE_NAME
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/SERVICE_DOMAIN
---
name: pocket-id
working_dir: apps/pocket-id
compose_files:
  - compose.pocket-id.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  APP_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/security/pocket-id/APP_URL
  ENCRYPTION_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/security/pocket-id/ENCRYPTION_KEY
  MAXMIND_LICENSE_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/security/pocket-id/MAXMIND_LICENSE_KEY
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/security/pocket-id/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/security/pocket-id/SERVICE_NAME
  ROOT_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ROOT_DOMAIN
  PANGOLIN_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/PANGOLIN_DOMAIN
---
name: pricebuddy
working_dir: apps/pricebuddy
compose_files:
  - compose.pricebuddy.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/pricebuddy/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/pricebuddy/SERVICE_NAME
  APP_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/pricebuddy/APP_KEY
  APP_USER_EMAIL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/pricebuddy/APP_USER_EMAIL
  APP_USER_PASSWORD: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/pricebuddy/APP_USER_PASSWORD
  DB_PASSWORD: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/pricebuddy/DB_PASSWORD
---
name: jellyfin
working_dir: apps/jellyfin
compose_files:
  - compose.jellyfin.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/media/jellyfin/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/media/jellyfin/SERVICE_NAME
---
name: openclaw
working_dir: apps/openclaw
compose_files:
  - compose.openclaw.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/openclaw/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/openclaw/SERVICE_NAME
  OPENROUTER_API_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/openclaw/OPENROUTER_API_KEY
  AUTH_USERNAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/openclaw/AUTH_USERNAME
  AUTH_PASSWORD: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/openclaw/AUTH_PASSWORD
  OPENCLAW_GATEWAY_TOKEN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/openclaw/OPENCLAW_GATEWAY_TOKEN
  OPENCLAW_ALLOWED_ORIGINS: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/openclaw/OPENCLAW_ALLOWED_ORIGINS
  HOOKS_TOKEN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ai/openclaw/HOOKS_TOKEN
---
name: n8n
working_dir: apps/n8n
compose_files:
  - compose.n8n.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/n8n/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/n8n/SERVICE_NAME
  N8N_HOST: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/n8n/N8N_HOST
  OIDC_CLIENT_ID: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/n8n/OIDC_CLIENT_ID
  OIDC_CLIENT_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/n8n/OIDC_CLIENT_SECRET
  OIDC_ISSUER_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/n8n/OIDC_ISSUER_URL
  OIDC_REDIRECT_URI: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/n8n/OIDC_REDIRECT_URI
  WEBHOOK_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/n8n/WEBHOOK_URL
---
name: doco-cd-vm-01-main
working_dir: apps/doco-cd
compose_files:
  - compose.updater-vm-01.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/SERVICE_NAME
  SECRET_PROVIDER: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/SECRET_PROVIDER
  SECRET_PROVIDER_SITE_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/SECRET_PROVIDER_SITE_URL
  SECRET_PROVIDER_CLIENT_ID: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/SECRET_PROVIDER_CLIENT_ID
  SECRET_PROVIDER_CLIENT_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/SECRET_PROVIDER_CLIENT_SECRET
  GIT_ACCESS_TOKEN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/GIT_ACCESS_TOKEN
