name: backrest
working_dir: apps/core/backrest
compose_files:
  - compose.backrest.yaml
remove_orphans: true
force_image_pull: true
external_secrets:
  BACKUP_USER: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/backrest/BACKUP_USER
  BACKUP_PASS: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/backrest/BACKUP_PASS
---
name: bunkerweb
working_dir: apps/core/bunkerweb
compose_files:
  - compose.bunkerweb.yaml
remove_orphans: true
force_image_pull: true
external_secrets:
  ADMIN_USER: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/bunkerweb/ADMIN_USER
  ADMIN_PASSWORD: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/bunkerweb/ADMIN_PASSWORD
  BWUI_PROXY_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/bunkerweb/BWUI_PROXY_URL
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/bunkerweb/SERVICE_DOMAIN
  BUNKERWEB_SERVER_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/bunkerweb/BUNKERWEB_SERVER_NAME
  BUNKERWEB_DB_PASSWORD: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/bunkerweb/BUNKERWEB_DB_PASSWORD
  BUNKERWEB_DATABASE_URI: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/bunkerweb/BUNKERWEB_DATABASE_URI
  TOTP_ENCRYPTION_KEYS: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/bunkerweb/TOTP_ENCRYPTION_KEYS
  ROOT_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ROOT_DOMAIN
  EMAIL_LETS_ENCRYPT: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/bunkerweb/EMAIL_LETS_ENCRYPT
  LETS_ENCRYPT_DNS_CREDENTIAL_ITEM: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/bunkerweb/LETS_ENCRYPT_DNS_CREDENTIAL_ITEM
  SECURITYTXT_CONTACT: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/bunkerweb/SECURITYTXT_CONTACT
  BUNKERWEB_SESSIONS_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/bunkerweb/BUNKERWEB_SESSIONS_SECRET
  ANTIBOT_TURNSTILE_SITEKEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/bunkerweb/ANTIBOT_TURNSTILE_SITEKEY
  ANTIBOT_TURNSTILE_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/bunkerweb/ANTIBOT_TURNSTILE_SECRET
---
name: cloudflared
working_dir: apps/core/cloudflared
compose_files:
  - compose.cloudflared.yaml
remove_orphans: true
force_image_pull: true
external_secrets:
  TUNNEL_TOKEN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/cloudflared/TUNNEL_TOKEN
#---
#name: doco-cd
#working_dir: apps/core/doco-cd
#compose_files:
#  - compose.doco-cd.yaml
#remove_orphans: true
#force_image_pull: true
#external_secrets:
#  GIT_ACCESS_TOKEN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/GIT_ACCESS_TOKEN
#  POLL_CONFIG_REPO_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/POLL_CONFIG_REPO_URL
#  SECRET_PROVIDER: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/SECRET_PROVIDER
#  SECRET_PROVIDER_CLIENT_ID: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/SECRET_PROVIDER_CLIENT_ID
#  SECRET_PROVIDER_CLIENT_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/SECRET_PROVIDER_CLIENT_SECRET
#  SECRET_PROVIDER_SITE_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/SECRET_PROVIDER_SITE_URL
#---
#name: traefik
#working_dir: apps/core/traefik
#compose_files:
#  - compose.traefik.yaml
#remove_orphans: true
#force_image_pull: true
#external_secrets:
#  CLOUDFLARE_API_EMAIL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/CLOUDFLARE_API_EMAIL
#  CLOUDFLARE_DNS_API_TOKEN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/CLOUDFLARE_DNS_API_TOKEN
#  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/SERVICE_DOMAIN
#  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/SERVICE_NAME
#  ROOT_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ROOT_DOMAIN
#  OIDC_SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/security/pocket-id/SERVICE_DOMAIN
#  TRAEFIK_OIDC_CLIENT_ID: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/TRAEFIK_OIDC_CLIENT_ID
#  TRAEFIK_OIDC_CLIENT_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/TRAEFIK_OIDC_CLIENT_SECRET
---
name: vaultwarden
working_dir: apps/core/vaultwarden
compose_files:
  - compose.vaultwarden.yaml
remove_orphans: true
force_image_pull: true
external_secrets:
  ADMIN_TOKEN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/ADMIN_TOKEN
  EXPERIMENTAL_CLIENT_FEATURE_FLAGS: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/EXPERIMENTAL_CLIENT_FEATURE_FLAGS
  DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/DOMAIN
  SMTP_HOST: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SMTP_HOST
  SMTP_FROM: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SMTP_FROM
  SMTP_USERNAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SMTP_USERNAME
  SMTP_PASSWORD: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SMTP_PASSWORD
  SSO_AUTHORITY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SSO_AUTHORITY
  SSO_CLIENT_ID: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SSO_CLIENT_ID
  SSO_CLIENT_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SSO_CLIENT_SECRET
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/SERVICE_NAME
  OIDC_PROVIDER_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/OIDC_PROVIDER_DOMAIN
  VAULTWARDEN_BASIC_USER: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/VAULTWARDEN_BASIC_USER
  VAULTWARDEN_BASIC_PASSWORD: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/vaultwarden/VAULTWARDEN_BASIC_PASSWORD
---
name: whoami
working_dir: apps/core/whoami
compose_files:
  - compose.whoami.yaml
remove_orphans: true
force_image_pull: true
external_secrets:
  TEST_VAR: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/whoami/TEST_VAR
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/whoami/SERVICE_NAME
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/whoami/SERVICE_DOMAIN
---
name: speedtest-tracker
working_dir: apps/monitoring/speedtest-tracker
compose_files:
  - compose.speedtest-tracker.yaml
remove_orphans: true
force_image_pull: true
external_secrets:
  APP_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/monitoring/speedtest-tracker/APP_KEY
  APP_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/monitoring/speedtest-tracker/APP_URL
  SPEEDTEST_SERVERS: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/monitoring/speedtest-tracker/SPEEDTEST_SERVERS
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/monitoring/speedtest-tracker/SERVICE_NAME
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/monitoring/speedtest-tracker/SERVICE_DOMAIN
---
name: forgejo
working_dir: apps/ops/forgejo
compose_files:
  - compose.forgejo.yaml
remove_orphans: true
force_image_pull: true
external_secrets:
  CF_CAPTCHA_SITEKEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/CF_CAPTCHA_SITEKEY
  CF_CAPTCHA_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/CF_CAPTCHA_SECRET
  MAIL_FROM: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/MAIL_FROM
  MAIL_HOST: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/MAIL_HOST
  MAIL_USER: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/MAIL_USER
  MAIL_PASSWD: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/MAIL_PASSWD
  NO_REPLY_ADDRESS: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/NO_REPLY_ADDRESS
  ROOT_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/ROOT_URL
  DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/DOMAIN
  SSH_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/SSH_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/SERVICE_NAME
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ops/forgejo/SERVICE_DOMAIN
---
name: crowdsec
working_dir: apps/security/crowdsec
compose_files:
  - compose.crowdsec.yaml
remove_orphans: true
force_image_pull: true
---
name: pocket-id
working_dir: apps/security/pocket-id
compose_files:
  - compose.pocket-id.yaml
remove_orphans: true
force_image_pull: true
external_secrets:
  APP_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/security/pocket-id/APP_URL
  ENCRYPTION_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/security/pocket-id/ENCRYPTION_KEY
  MAXMIND_LICENSE_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/security/pocket-id/MAXMIND_LICENSE_KEY
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/security/pocket-id/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/security/pocket-id/SERVICE_NAME
  ROOT_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ROOT_DOMAIN
---
name: immich
working_dir: apps/storage/immich
compose_files:
  - compose.immich.yaml
remove_orphans: true
force_image_pull: true
external_secrets:
  DB_DATABASE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/storage/immich/DB_DATABASE_NAME
  DB_PASSWORD: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/storage/immich/DB_PASSWORD
  DB_USERNAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/storage/immich/DB_USERNAME
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/storage/immich/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/storage/immich/SERVICE_NAME
---
name: homebox
working_dir: apps/tools/homebox
compose_files:
  - compose.homebox.yaml
remove_orphans: true
force_image_pull: true
external_secrets:
  HBOX_OIDC_ISSUER_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/homebox/HBOX_OIDC_ISSUER_URL
  HBOX_OIDC_CLIENT_ID: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/homebox/HBOX_OIDC_CLIENT_ID
  HBOX_OIDC_CLIENT_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/homebox/HBOX_OIDC_CLIENT_SECRET
  HBOX_MAILER_HOST: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/homebox/HBOX_MAILER_HOST
  HBOX_MAILER_USERNAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/homebox/HBOX_MAILER_USERNAME
  HBOX_MAILER_PASSWORD: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/homebox/HBOX_MAILER_PASSWORD
  HBOX_MAILER_FROM: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/homebox/HBOX_MAILER_FROM
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/homebox/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/homebox/SERVICE_NAME
---
name: n8n
working_dir: apps/automation/n8n
compose_files:
  - compose.n8n.yaml
remove_orphans: true
force_image_pull: true
external_secrets:
  N8N_HOST: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/n8n/N8N_HOST
  WEBHOOK_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/n8n/WEBHOOK_URL
  OIDC_ISSUER_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/n8n/OIDC_ISSUER_URL
  OIDC_CLIENT_ID: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/n8n/OIDC_CLIENT_ID
  OIDC_CLIENT_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/n8n/OIDC_CLIENT_SECRET
  OIDC_REDIRECT_URI: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/n8n/OIDC_REDIRECT_URI
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/n8n/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/automation/n8n/SERVICE_NAME
---
name: ntfy
working_dir: apps/tools/ntfy
compose_files:
  - compose.ntfy.yaml
remove_orphans: true
force_image_pull: true
external_secrets:
  NTFY_BASE_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/ntfy/NTFY_BASE_URL
  NTFY_WEB_PUSH_PUBLIC_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/ntfy/NTFY_WEB_PUSH_PUBLIC_KEY
  NTFY_WEB_PUSH_PRIVATE_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/ntfy/NTFY_WEB_PUSH_PRIVATE_KEY
  NTFY_WEB_PUSH_EMAIL_ADDRESS: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/ntfy/NTFY_WEB_PUSH_EMAIL_ADDRESS
  NTFY_SMTP_SENDER_ADDR: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/ntfy/NTFY_SMTP_SENDER_ADDR
  NTFY_SMTP_SENDER_FROM: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/ntfy/NTFY_SMTP_SENDER_FROM
  NTFY_SMTP_SENDER_USER: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/ntfy/NTFY_SMTP_SENDER_USER
  NTFY_SMTP_SENDER_PASS: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/ntfy/NTFY_SMTP_SENDER_PASS
  NTFY_AUTH_USERS: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/ntfy/NTFY_AUTH_USERS
  NTFY_OIDC_ISSUER_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/ntfy/NTFY_OIDC_ISSUER_URL
  NTFY_OIDC_CLIENT_ID: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/ntfy/NTFY_OIDC_CLIENT_ID
  NTFY_OIDC_CLIENT_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/ntfy/NTFY_OIDC_CLIENT_SECRET
  NTFY_OIDC_SESSION_ENCRYPTION_KEY: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/ntfy/NTFY_OIDC_SESSION_ENCRYPTION_KEY
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/ntfy/SERVICE_NAME
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/tools/ntfy/SERVICE_DOMAIN
