---
name: dms
working_dir: apps/dms
compose_files:
  - compose.dms.yaml
remove_orphans: true
force_image_pull: true
external_secrets:
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/dms/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/dms/SERVICE_NAME
  MAILSERVER_HOSTNAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/dms/MAILSERVER_HOSTNAME
  AUTODISCOVER_SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/dms/AUTODISCOVER_SERVICE_NAME
  AUTODISCOVER_SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/dms/AUTODISCOVER_SERVICE_DOMAIN
  COMPANY_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/dms/COMPANY_NAME
  IMAP_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/dms/IMAP_DOMAIN
  SMTP_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/dms/SMTP_DOMAIN