name: netbird
working_dir: apps/netbird
compose_files:
  - compose.netbird.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  SERVICE_DOMAIN: a1db37a1-167f-46f0-b63f-657d5afe43c5:prod:/security/netbird/SERVICE_DOMAIN
  SERVICE_NAME: a1db37a1-167f-46f0-b63f-657d5afe43c5:prod:/security/netbird/SERVICE_NAME
  NB_PROXY_TOKEN: a1db37a1-167f-46f0-b63f-657d5afe43c5:prod:/security/netbird/NB_PROXY_TOKEN
---
name: pocket-id
working_dir: apps/pocket-id
compose_files:
  - compose.pocket-id.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  APP_URL: a1db37a1-167f-46f0-b63f-657d5afe43c5:prod:/security/pocket-id/APP_URL
  ENCRYPTION_KEY: a1db37a1-167f-46f0-b63f-657d5afe43c5:prod:/security/pocket-id/ENCRYPTION_KEY
  MAXMIND_LICENSE_KEY: a1db37a1-167f-46f0-b63f-657d5afe43c5:prod:/security/pocket-id/MAXMIND_LICENSE_KEY
  SERVICE_DOMAIN: a1db37a1-167f-46f0-b63f-657d5afe43c5:prod:/security/pocket-id/SERVICE_DOMAIN
  SERVICE_NAME: a1db37a1-167f-46f0-b63f-657d5afe43c5:prod:/security/pocket-id/SERVICE_NAME
  ROOT_DOMAIN: a1db37a1-167f-46f0-b63f-657d5afe43c5:prod:/ROOT_DOMAIN
  PANGOLIN_DOMAIN: a1db37a1-167f-46f0-b63f-657d5afe43c5:prod:/PANGOLIN_DOMAIN
