---
name: traefik
working_dir: apps/traefik
compose_files:
  - compose.traefik.yaml
remove_orphans: true
force_image_pull: true
external_secrets:
  CLOUDFLARE_API_EMAIL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/CLOUDFLARE_API_EMAIL
  CLOUDFLARE_DNS_API_TOKEN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/CLOUDFLARE_DNS_API_TOKEN
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/SERVICE_NAME
  ROOT_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/ROOT_DOMAIN
  OIDC_SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/security/pocket-id/SERVICE_DOMAIN
  TRAEFIK_OIDC_CLIENT_ID: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/TRAEFIK_OIDC_CLIENT_ID
  TRAEFIK_OIDC_CLIENT_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/traefik/TRAEFIK_OIDC_CLIENT_SECRET
---
name: dms
working_dir: apps/dms
compose_files:
  - compose.dms.yaml
remove_orphans: true
force_image_pull: true
external_secrets:
  SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/dms/SERVICE_DOMAIN
  SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/dms/SERVICE_NAME
  MAILSERVER_HOSTNAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/dms/MAILSERVER_HOSTNAME
  AUTODISCOVER_SERVICE_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/dms/AUTODISCOVER_SERVICE_NAME
  AUTODISCOVER_SERVICE_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/dms/AUTODISCOVER_SERVICE_DOMAIN
  COMPANY_NAME: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/dms/COMPANY_NAME
  IMAP_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/dms/IMAP_DOMAIN
  SMTP_DOMAIN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/dms/SMTP_DOMAIN