---
name: doco-cd-vm-01-updater
working_dir: apps/doco-cd
compose_files:
  - compose.main-vm-01.yaml
remove_orphans: true
force_image_pull: false
external_secrets:
  POLL_CONFIG_REPO_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/POLL_CONFIG_REPO_URL
  SECRET_PROVIDER: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/SECRET_PROVIDER
  SECRET_PROVIDER_SITE_URL: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/SECRET_PROVIDER_SITE_URL
  SECRET_PROVIDER_CLIENT_ID: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/SECRET_PROVIDER_CLIENT_ID
  SECRET_PROVIDER_CLIENT_SECRET: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/SECRET_PROVIDER_CLIENT_SECRET
  GIT_ACCESS_TOKEN: 65a92749-709e-4cfc-97a7-1bb81d09182e:prod:/core/doco-cd/GIT_ACCESS_TOKEN