services:
  nexus3:
    image: sonatype/nexus3:latest@sha256:5f48f9085096e96f4111ec07d79d57ca5a4a1da5a2003a3028a0b60c62bea7d1
    #ports:
    #  - 8081:8081
    container_name: nexus
    hostname: nexus
    environment:
      - NEXUS_SECRETS_KEY_FILE=/opt/sonatype/nexus/etc/nexus.secrets.json
    volumes:
      - /srv/ops/nexus/data:/nexus-data
      - /srv/ops/nexus/config/nexus.secrets.json:/opt/sonatype/nexus/etc/nexus.secrets.json:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=cloudflare"
      # - "traefik.http.routers.${SERVICE_NAME}.middlewares=cloudflarewarp@file,crowdsec@file"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=8081"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
