services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:1.15.0@sha256:dc439a8bbadd3d0d4a4af4ee64bf30a6db9ced425c00ac12ea2ff04e15669ed1
    container_name: speedtest-tracker
    hostname: speedtest-tracker
    restart: always
#    ports:
#      - 8080:80
#      - 8443:443
    environment:
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE="0 */1 * * *"
      - SPEEDTEST_SERVERS=${SPEEDTEST_SERVERS}
      - APP_TIMEZONE=Europe/Berlin
      - DISPLAY_TIMEZONE=Europe/Berlin
    volumes:
      - /srv/monitoring/speedtest-tracker/data:/config
      
      # localtime mount
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=cloudflare"
      # - "traefik.http.routers.${SERVICE_NAME}.middlewares=cloudflarewarp@file,crowdsec@file"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
