services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.5.0@sha256:1549f31f76a6c158af0056a4f2c62a590627886a84e9da9bda76eb1e142a449a
    container_name: pocket-id
    hostname: pocket-id
    restart: unless-stopped
    environment:
      APP_URL: ${APP_URL}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY}
      TRUST_PROXY: "true"
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Berlin"
#    ports:
#      - 1411:1411
    volumes:
      - "/mnt/ssd/security/pocket-id/data:/app/data"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - bw-services
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    labels:
      - "bunkerweb.SERVER_NAME=${SERVICE_DOMAIN}"
      - "bunkerweb.USE_REVERSE_PROXY=yes"
      - "bunkerweb.REVERSE_PROXY_URL=/"
      - "bunkerweb.REVERSE_PROXY_HOST=http://pocket-id:1411"
      - "bunkerweb.SECURITY_MODE=detect"
      - "bunkerweb.USE_LIMIT_REQ=yes"
      - "bunkerweb.LIMIT_REQ_URL=/"
      - "bunkerweb.LIMIT_REQ_RATE=100r/m"
      - "bunkerweb.LIMIT_REQ_URL_1=/authorize"
      - "bunkerweb.LIMIT_REQ_RATE_1=15r/m"
      - "bunkerweb.LIMIT_REQ_URL_2=/api/oidc/token"
      - "bunkerweb.LIMIT_REQ_RATE_2=50r/m"
      - "bunkerweb.LIMIT_REQ_URL_3=/api/oidc/userinfo"
      - "bunkerweb.LIMIT_REQ_RATE_3=80r/m"
      - "bunkerweb.BAD_BEHAVIOR_THRESHOLD=8"
      - "bunkerweb.CORS_ORIGIN=*.${ROOT_DOMAIN}"
      - "bunkerweb.CORS_CREDENTIALS=yes"
      - "bunkerweb.CORS_METHODS=GET,POST,OPTIONS,PUT,DELETE"
      - "bunkerweb.CORS_HEADERS=Authorization,Content-Type,X-Requested-With"
      - "bunkerweb.USE_CSP=no"
      - "bunkerweb.MODSECURITY_SEC_RULE_ENGINE=OnDetectionOnly"
      - "bunkerweb.USE_ANTIBOT=no"
      - "bunkerweb.CONTENT_SECURITY_POLICY=default-src 'self' data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; manifest-src 'self' https://${PANGOLIN_DOMAIN} https://${SERVICE_DOMAIN};"
      - "bunkerweb.PERMISSIONS_POLICY=geolocation=() microphone=() camera=() local-network=() private-network=() publickey-credentials=(self)"

networks:
  bw-services:
    external: true