services:
  litellm-db:
    image: postgres:15@sha256:9b1d34adbce1dd07ee6e94b4a2cf698884b89bd44a6c9c12f5da8f3acbfe4957
    container_name: litellm-db
    hostname: litellm-db
    restart: always
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: ${LITELLM_DB_PASSWORD}
    volumes:
      - /srv/ai/litellm/db:/var/lib/postgresql/data
      
      # localtime mount
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U litellm -d litellm"]
      interval: 5s
      timeout: 5s
      retries: 5

  litellm:
    image: ghcr.io/berriai/litellm:v1.98.0@sha256:20b5044b619055374061a6d5b7b08754cad75aeabbf82ddf4f69cc0cf80ddaf4
    container_name: litellm
    hostname: litellm
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENCODE_GO_API_KEY_1=${OPENCODE_GO_API_KEY_1}
      - OPENCODE_GO_API_KEY_2=${OPENCODE_GO_API_KEY_2}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - LITELLM_LOG=INFO
      - OPENAI_BASE_URL=${OPENROUTER_API_URL}
      - DATABASE_URL=${LITELLM_DB_URL}
      - STORE_MODEL_IN_DB=true
      - LITELLM_MODEL_COST_MAP_URL=https://cloudprice.net/api/v2/ai/litellm_model_prices.json
      - CHATGPT_TOKEN_DIR=/app/chatgpt-tokens
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_BASE_URL=${LANGFUSE_BASE_URL}
      #- SERVER_ROOT_PATH=/api/
    volumes:
      - /srv/ai/litellm/data:/etc/litellm
      - /srv/ai/litellm/chatgpt-tokens:/app/chatgpt-tokens
      # localtime mount
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
      - traefik
    entrypoint:
      - sh
      - -c
      - |
        exec litellm --config /etc/litellm/config.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=cloudflare"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=4000"
      - "traefik.docker.network=traefik"

networks:
  default:
    name: litellm
  traefik:
    external: true
