services:
  litellm-db:
    image: postgres:15@sha256:6eb0add3b77c081df18aa518ce43df58fdcc40f2e6d868a6fd08038dc7acd425
    container_name: litellm-db
    hostname: litellm-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: ${LITELLM_DB_PASSWORD}
    volumes:
      - /srv/ai/litellm/db:/var/lib/postgresql/data
      
      # localtime mount
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U litellm -d litellm"]
      interval: 5s
      timeout: 5s
      retries: 5

  litellm:
    image: ghcr.io/berriai/litellm:v1.95.0@sha256:af806882b7a6ced41658db5b6a7e98ed7b9b51d03b935e0417bf1c8552d688af
    container_name: litellm
    hostname: litellm
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENCODE_GO_API_KEY_1=${OPENCODE_GO_API_KEY_1}
      - OPENCODE_GO_API_KEY_2=${OPENCODE_GO_API_KEY_2}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - LITELLM_LOG=INFO
      - OPENAI_BASE_URL=${OPENROUTER_API_URL}
      - DATABASE_URL=${LITELLM_DB_URL}
      - STORE_MODEL_IN_DB=true
      - LITELLM_MODEL_COST_MAP_URL=https://cloudprice.net/api/v2/ai/litellm_model_prices.json
      - CHATGPT_TOKEN_DIR=/app/chatgpt-tokens
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_BASE_URL=${LANGFUSE_BASE_URL}
      #- SERVER_ROOT_PATH=/api/
    volumes:
      - /srv/ai/litellm/data:/etc/litellm
      - /srv/ai/litellm/chatgpt-tokens:/app/chatgpt-tokens
      # localtime mount
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
      - traefik
    entrypoint:
      - sh
      - -c
      - |
        exec litellm --config /etc/litellm/config.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=cloudflare"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=4000"
      - "traefik.docker.network=traefik"

networks:
  default:
    name: litellm
  traefik:
    external: true
