services:

  searxng-redis:
    image: valkey/valkey:9-alpine@sha256:a0dbf4c1d5708782907c10e2c72deff317518518b5288a58416981d9db95d30b
    container_name: searxng-redis
    hostname: searxng-redis
    restart: always
    command: valkey-server --save 30 1 --loglevel warning

    networks:
      - searxng
    volumes:
      - /srv/automation/searxng/valkey-data2:/data
      
      # localtime mount
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    image: searxng/searxng:latest@sha256:1dab138ea70a8ceb4d1c182f5c8f256088406c1742b99e279976157dbe1e9759
    container_name: searxng
    hostname: searxng
    restart: always
    networks:
      - searxng
      - traefik
    #ports:
    #  - "127.0.0.1:8002:8080"
    volumes:
      - /srv/automation/searxng/config:/etc/searxng:rw
      - /srv/automation/searxng/data:/var/cache/searxng:rw
      
      # localtime mount
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SEARXNG_BASE_URL=https://${SERVICE_DOMAIN}/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=cloudflare"
      # - "traefik.http.routers.${SERVICE_NAME}.middlewares=cloudflarewarp@file,crowdsec@file"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
  searxng:
