services:

  searxng-redis:
    image: valkey/valkey:9-alpine@sha256:c9b77919daeba2c02ad954d0c844cc4e7142069d177b89c5fd771f405daf9e02
    container_name: searxng-redis
    hostname: searxng-redis
    restart: unless-stopped
    command: valkey-server --save 30 1 --loglevel warning

    networks:
      - searxng
    volumes:
      - /srv/automation/searxng/valkey-data2:/data
      
      # localtime mount
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    image: searxng/searxng:latest@sha256:800a5e3757df04f59e6bd6c622f15de2edbfa47f5591c5b82d4a8ff3b938a845
    container_name: searxng
    hostname: searxng
    restart: unless-stopped
    networks:
      - searxng
      - traefik
    #ports:
    #  - "127.0.0.1:8002:8080"
    volumes:
      - /srv/automation/searxng/config:/etc/searxng:rw
      - /srv/automation/searxng/data:/var/cache/searxng:rw
      
      # localtime mount
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SEARXNG_BASE_URL=https://${SERVICE_DOMAIN}/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=cloudflare"
      # - "traefik.http.routers.${SERVICE_NAME}.middlewares=cloudflarewarp@file,crowdsec@file"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
  searxng:
