services:

  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.7@sha256:6ca53ad26196ca59ddd4fa692a586b73d8fcde085046163b9ca2f04887dca563
    container_name: crowdsec
    hostname: crowdsec
    restart: unless-stopped
    ports:
      - 127.0.0.1:9876:8080 # port mapping for local firewall bouncers
    expose:
      - 8080 # http api for bouncers
      - 6060 # metrics endpoint for prometheus
      - 7422 # appsec waf endpoint
    volumes:
      # crowdsec container data
      - /mnt/ssd/security/crowdsec/data:/var/lib/crowdsec/data
      - /mnt/ssd/security/crowdsec/etc:/etc/crowdsec
      # log bind mounts into crowdsec
      #- /var/log/auth.log:/var/log/auth.log:ro
      #- /var/log/syslog:/var/log/syslog:ro
      - /mnt/hdd/logs/traefik/access.log:/var/log/traefik/access.log:ro

    environment:
      - GID=1000
      - COLLECTIONS=crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios crowdsecurity/sshd crowdsecurity/linux crowdsecurity/appsec-generic-rules crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-crs
      #- CUSTOM_HOSTNAME=my-crowdsec-host123
    networks:
      - traefik

networks:
  traefik:
    external: true