services:
  vane:
    image: itzcrazykns1337/vane:slim-v1.12.2
    # ports:
    #   - '3000:3000'
    volumes:
      - data:/home/vane/data
    environment:
      SEARXNG_API_URL: ${SEARXNG_API_URL}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=cloudflare"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"

volumes:
  data:
    name: 'vane-data'