services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.76.0@sha256:ef0df49fca5ccaa4c4e01e13bf99d15609c093dd08f53f0c94dacac2a72ed4bd
    container_name: doco-cd
    hostname: doco-cd
    environment:
      POLL_CONFIG: |
        - url: ${POLL_CONFIG_REPO_URL}
          reference: main
          interval: 60
      SECRET_PROVIDER: ${SECRET_PROVIDER}
      SECRET_PROVIDER_SITE_URL: ${SECRET_PROVIDER_SITE_URL}
      SECRET_PROVIDER_CLIENT_ID: ${SECRET_PROVIDER_CLIENT_ID}
      SECRET_PROVIDER_CLIENT_SECRET: ${SECRET_PROVIDER_CLIENT_SECRET}
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      TZ: Europe/Berlin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/ssd/core/doco-cd/data:/data
    labels:
      - "traefik.enable=false"
