services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:15.1.0@sha256:af51b15dd3fc72153c0e90eb7692bb5e3a463212d87959a80fa7aa89b617d44a
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: ${MAILSERVER_HOSTNAME}
    environment:
      - LOG_LEVEL=info
      - SUPERVISOR_LOGLEVEL=warn
      - DMS_VMAIL_UID=
      - DMS_VMAIL_GID=
      - ACCOUNT_PROVISIONER=
      - POSTMASTER_ADDRESS=postmaster@${MAIL_DOMAIN}
      - ENABLE_UPDATE_CHECK=0
      - UPDATE_CHECK_INTERVAL=1d
      - PERMIT_DOCKER=none
      - TZ=Europe/Berlin
      
      - ENABLE_RSPAMD=1
      - ENABLE_RSPAMD_REDIS=1
      - ENABLE_POLICYD_SPF=0
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_OPENDKIM=1
      - ENABLE_OPENDMARC=1
      - SPOOF_PROTECTION=1
      - ENABLE_SRS=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_MTA_STS=1

      - ENABLE_IMAP=1
      - ENABLE_POP3=0
      - ENABLE_MANAGESIEVE=1

      - POSTSCREEN_ACTION=enforce
      - MOVE_SPAM_TO_JUNK=1
      - MARK_SPAM_AS_READ=0

    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /srv/core/dms/docker-data/dms/mail-data/:/var/mail/
      - /srv/core/dms/docker-data/dms/mail-state/:/var/mail-state/
      - /srv/core/dms/docker-data/dms/mail-logs/:/var/log/mail/
      - /srv/core/dms/docker-data/dms/config/:/tmp/docker-mailserver/

      # bind mount for certs
      - /etc/letsencrypt:/etc/letsencrypt

      # localtime mount
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    cap_add:
      - NET_ADMIN

  autodiscover:
    image: monogramm/autodiscover-email-settings:latest@sha256:4a9706ab469aff8e610bb2a4e22fe9c19216c571d2471e85941b2d3d5f4e6f28
    container_name: autodiscover
    hostname: autodiscover
    environment:
      - COMPANY_NAME=${COMPANY_NAME}
      - SUPPORT_URL=https://${AUTODISCOVER_SERVICE_DOMAIN}
      - DOMAIN=${AUTODISCOVER_SERVICE_DOMAIN}
      # IMAP configuration (host mandatory to enable)
      - IMAP_HOST=${IMAP_DOMAIN}
      - IMAP_PORT=993
      - IMAP_SOCKET=SSL
      # SMTP configuration (host mandatory to enable)
      - SMTP_HOST=${SMTP_DOMAIN}
      - SMTP_PORT=587
      - SMTP_SOCKET=STARTTLS
    networks:
      - dms_network

networks:
  dms_network:
    external: true
