services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:1.13.12
    container_name: speedtest-tracker
    hostname: speedtest-tracker
    restart: unless-stopped
#    ports:
#      - 8080:80
#      - 8443:443
    environment:
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE="0 */1 * * *"
      - SPEEDTEST_SERVERS=${SPEEDTEST_SERVERS}
      - APP_TIMEZONE=Europe/Berlin
      - DISPLAY_TIMEZONE=Europe/Berlin
    volumes:
      - /mnt/ssd/monitoring/speedtest-tracker/data:/config
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=cloudflare"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=cloudflarewarp@file,crowdsec@file"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
