services:
  mcpo:
    image: ghcr.io/open-webui/mcpo:main@sha256:1e82c9555c19e50b80745705f32b47a2647589f35279527b5118ecd3a71bd467
    container_name: mcpo
    hostname: mcpo
    volumes:
      - /srv/ai/open-webui/mcpo/config:/config
      - /srv/ai/open-webui/mcpo/data:/mcpo-data
      - /srv/ai/open-webui/mcpo/cache:/mcpo-cache
      - /srv/ai/open-webui/mcpo/userdata:/data/user
    command: >
      --port 8000
      --root-path "/api"
      --api-key "${MCPO_API_KEY}"
      --config /config/config.json
      --hot-reload
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcpo-${SERVICE_NAME}.rule=Host(`mcpo.${SERVICE_DOMAIN}`)"
      - "traefik.http.routers.mcpo-${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.services.mcpo-${SERVICE_NAME}.loadbalancer.server.port=8000"
      - "traefik.http.routers.mcpo-${SERVICE_NAME}.service=mcpo-${SERVICE_NAME}"
      - "traefik.http.routers.mcpo-${SERVICE_NAME}.tls.certresolver=cloudflare"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
