services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.99.0@sha256:027be49dc467fbd1440446135813ac5aaa6795ee36bf306d1dc0a3b36d00d697
    container_name: doco-cd
    hostname: doco-cd
    environment:
      POLL_CONFIG: |
        - url: ${POLL_CONFIG_REPO_URL}
          reference: main
          interval: 60
          target: main-vm-01
      SECRET_PROVIDER: ${SECRET_PROVIDER}
      SECRET_PROVIDER_SITE_URL: ${SECRET_PROVIDER_SITE_URL}
      SECRET_PROVIDER_CLIENT_ID: ${SECRET_PROVIDER_CLIENT_ID}
      SECRET_PROVIDER_CLIENT_SECRET: ${SECRET_PROVIDER_CLIENT_SECRET}
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      TZ: Europe/Berlin
      DOCKER_SWARM_FEATURES: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/data
    labels:
      - "traefik.enable=false"

volumes:
  data: