services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.101.0@sha256:21bbf705ebe1cbc21afbca6f9af777d61dfe54549e40000d0533be7d8c4beafe
    container_name: doco-cd-updater
    hostname: doco-cd-updater
    environment:
      POLL_CONFIG: |
        - url: ${POLL_CONFIG_REPO_URL}
          reference: main
          interval: 300
          target: updater-dashserv
      SCHEDULER_ENABLED: false
      SECRET_PROVIDER: ${SECRET_PROVIDER}
      SECRET_PROVIDER_SITE_URL: ${SECRET_PROVIDER_SITE_URL}
      SECRET_PROVIDER_CLIENT_ID: ${SECRET_PROVIDER_CLIENT_ID}
      SECRET_PROVIDER_CLIENT_SECRET: ${SECRET_PROVIDER_CLIENT_SECRET}
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      TZ: Europe/Berlin
      DOCKER_SWARM_FEATURES: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/envs:/srv/envs:ro
      - updater-data:/data
    labels:
      - "traefik.enable=false"

volumes:
  updater-data: