services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.115.0@sha256:c816fd7d4bac3e02fb5b650e2cca2104b058200fa57432be9a992a9591504381
    container_name: doco-cd-updater
    hostname: doco-cd-updater
    environment:
      POLL_CONFIG: |
        - url: ${POLL_CONFIG_REPO_URL}
          reference: main
          interval: 300
          target: updater-nb-vps
      SCHEDULER_ENABLED: false
      SECRET_PROVIDER: ${SECRET_PROVIDER}
      SECRET_PROVIDER_SITE_URL: ${SECRET_PROVIDER_SITE_URL}
      SECRET_PROVIDER_CLIENT_ID: ${SECRET_PROVIDER_CLIENT_ID}
      SECRET_PROVIDER_CLIENT_SECRET: ${SECRET_PROVIDER_CLIENT_SECRET}
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      TZ: Europe/Berlin
      DOCKER_SWARM_FEATURES: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - updater-data:/data
    labels:
      - "traefik.enable=false"

volumes:
  updater-data: