services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.110.1@sha256:cd491cf9ec09e39f0e690a418e8a5e2c5d631544d6af8f879f4de8978b847af1
    container_name: doco-cd
    hostname: doco-cd
    restart: always
    environment:
      POLL_CONFIG: |
        - url: ${POLL_CONFIG_REPO_URL}
          reference: main
          interval: 300
          target: main-dashserv
      SECRET_PROVIDER: ${SECRET_PROVIDER}
      SECRET_PROVIDER_SITE_URL: ${SECRET_PROVIDER_SITE_URL}
      SECRET_PROVIDER_CLIENT_ID: ${SECRET_PROVIDER_CLIENT_ID}
      SECRET_PROVIDER_CLIENT_SECRET: ${SECRET_PROVIDER_CLIENT_SECRET}
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      TZ: Europe/Berlin
      DOCKER_SWARM_FEATURES: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/envs:/srv/envs:ro
      - data:/data
    labels:
      - "traefik.enable=false"

volumes:
  data: