services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.119.0@sha256:c0eedd8e81bc7d8dc83753cf0b1c7bdedf588400d826154ccb641b25f12c7770
    container_name: doco-cd
    hostname: doco-cd
    restart: always
    environment:
      POLL_CONFIG: |
        - url: ${POLL_CONFIG_REPO_URL}
          reference: main
          interval: 300
          target: main-nb-vps
      SECRET_PROVIDER: ${SECRET_PROVIDER}
      SECRET_PROVIDER_SITE_URL: ${SECRET_PROVIDER_SITE_URL}
      SECRET_PROVIDER_CLIENT_ID: ${SECRET_PROVIDER_CLIENT_ID}
      SECRET_PROVIDER_CLIENT_SECRET: ${SECRET_PROVIDER_CLIENT_SECRET}
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      TZ: Europe/Berlin
      DOCKER_SWARM_FEATURES: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/data
    labels:
      - "traefik.enable=false"

volumes:
  data: