services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.120.1@sha256:8799df51462a1b2058c60e35d1ce19830cc38afebe99494342e819cdaadad545
    container_name: doco-cd-updater
    hostname: doco-cd-updater
    environment:
      POLL_CONFIG: |
        - url: ${POLL_CONFIG_REPO_URL}
          reference: main
          interval: 300
          target: updater-nb-vps
      SCHEDULER_ENABLED: false
      SECRET_PROVIDER: ${SECRET_PROVIDER}
      SECRET_PROVIDER_SITE_URL: ${SECRET_PROVIDER_SITE_URL}
      SECRET_PROVIDER_CLIENT_ID: ${SECRET_PROVIDER_CLIENT_ID}
      SECRET_PROVIDER_CLIENT_SECRET: ${SECRET_PROVIDER_CLIENT_SECRET}
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      TZ: Europe/Berlin
      DOCKER_SWARM_FEATURES: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - updater-data:/data
    labels:
      - "traefik.enable=false"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

volumes:
  updater-data: