services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.100.0@sha256:4bf47fa47ee59245a6dbacd8643dd67401667b345841f7c3b31798251ae08885
    container_name: doco-cd
    hostname: doco-cd
    environment:
      POLL_CONFIG: |
        - url: ${POLL_CONFIG_REPO_URL}
          reference: main
          interval: 300
          target: main-dashserv
      SECRET_PROVIDER: ${SECRET_PROVIDER}
      SECRET_PROVIDER_SITE_URL: ${SECRET_PROVIDER_SITE_URL}
      SECRET_PROVIDER_CLIENT_ID: ${SECRET_PROVIDER_CLIENT_ID}
      SECRET_PROVIDER_CLIENT_SECRET: ${SECRET_PROVIDER_CLIENT_SECRET}
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      TZ: Europe/Berlin
      DOCKER_SWARM_FEATURES: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/envs:/srv/envs:ro
      - data:/data
    labels:
      - "traefik.enable=false"

volumes:
  data: