services:

  app:
    image: jez500/pricebuddy:v1.0.51@sha256:90e9cd7ceb68cfb3a00071468d6045e586a40605fc713f627ad7f5f0a8050948
    volumes:
      - /mnt/automation/pricebuddy/storage:/app/storage
    environment:
      DB_HOST: database                       # Name of the database service
      DB_USERNAME: pricebuddy                 # Should match the MYSQL_USER in the database service
      DB_PASSWORD: ${DB_PASSWORD}                # Should match the MYSQL_PASSWORD in the database service
      DB_DATABASE: pricebuddy                 # Should match the MYSQL_DATABASE in the database service
      APP_KEY: ${APP_KEY}                         # Should be a random 32 character string
      APP_USER_EMAIL: ${APP_USER_EMAIL}       # Only used for seeding the database
      APP_USER_PASSWORD: ${APP_USER_PASSWORD} # Only used for seeding the database
      SCRAPER_BASE_URL: http://scraper:3000   # Url to Name of the scrapper service
      AFFILIATE_ENABLED: 'true'               # See https://pricebuddy.jez.me/support-project.html
      APP_URL: https://${SERVICE_DOMAIN}            # The domain name of the service
      ASSET_URL: https://${SERVICE_DOMAIN} # The domain name of the service
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`$SERVICE_DOMAIN`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80"
      - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=cloudflare"
      - "traefik.docker.network=traefik"

  database:
    image: mysql:8.2@sha256:212fe73edca5df6ff14826d5eb975c914bfb91f82a2e923f9050568f99525da1
    environment:
      MYSQL_DATABASE: pricebuddy
      MYSQL_USER: pricebuddy
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /mnt/automation/pricebuddy/database:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1m

  scraper:
    image: jez500/seleniumbase-scrapper:v1.0@sha256:501895ba8e1f592b0480c870d10113b94f1a2ba3185dfaf89b41b9e36fe8f25f
    networks:
      - default
    #ports:
    #    - 3030:3000 # Optional, if you want to access the scrapper api from the host machine

networks:
  default:
  traefik:
    external: true