services:
  mcpo:
    image: ghcr.io/open-webui/mcpo:main@sha256:1e82c9555c19e50b80745705f32b47a2647589f35279527b5118ecd3a71bd467
    container_name: mcpo
    hostname: mcpo
    volumes:
      - /mnt/ai/mcpo/config:/config
      - /mnt/ai/mcpo/data:/mcpo-data
      - /mnt/ai/mcpo/cache:/mcpo-cache
    environment:
      - BASE_DIR=/mcpo-data/docs
    command: >
      --port 8000
      --root-path "/api"
      --api-key "${MCPO_API_KEY}"
      --config /config/config.json
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`$SERVICE_DOMAIN`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=8000"
      - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=cloudflare"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true