services:
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    init: true
    #ports:
    #  - 3000:3000
    restart: unless-stopped
    environment:
      # See README.md and config.default.yml for all config options
      WAKAPI_DB_TYPE: "postgres"
      WAKAPI_DB_NAME: "wakapi"
      WAKAPI_DB_USER: "wakapi"
      WAKAPI_DB_HOST: "db"
      WAKAPI_DB_PORT: "5432"
      WAKAPI_DB_PASSWORD: ${POSTGRES_PASSWORD}
      WAKAPI_PASSWORD_SALT: ${WAKAPI_PASSWORD_SALT}
      WAKAPI_MAIL_SMTP_USER: ${WAKAPI_MAIL_SMTP_USER}
      WAKAPI_MAIL_SMTP_PASS: ${WAKAPI_MAIL_SMTP_PASS}
      WAKAPI_MAIL_SMTP_HOST: ${WAKAPI_MAIL_SMTP_HOST}
      WAKAPI_MAIL_SMTP_PORT: "465"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=cloudflare"
      # - "traefik.http.routers.${SERVICE_NAME}.middlewares=cloudflarewarp@file,crowdsec@file"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik"

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: "wakapi"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "wakapi"
    volumes:
      - /mnt/ssd/ops/wakapi/db:/var/lib/postgresql/data

volumes:
  wakapi-db-data: {}