name: AI PR Title and Description Updater

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened, review_requested]

jobs:
  update-pr:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: PR Agent action step
        id: pragent
        uses: the-pr-agent/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI.API_BASE: ${{ secrets.OPENAI_API_BASE }}
          config.model: "google/gemini-2.5-flash-lite"
          config.fallback_models: '["google/gemini-2.5-flash-lite"]'
          pr_description.publish_description_as_comment: "false"
          pr_description.generate_ai_title: "true"
          pr_description.auto_create_ticket: "true"
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "true"
          github_action_config.pr_actions: '["opened", "reopened", "ready_for_review", "review_requested", "synchronize"]'
